### ISSUE TITLE
jfmutil error when converting vf 2 zvp

### ISSUE THREAD

**Issue by Steve-Cheung-emct** [zr-tex8r/PXutil#1]
Dear Mr. ZR.
Please help me. This error below eccored when converting vf 2 zvp.

>perl  jfmutil.pl  vf2zvp -u --lenient upjisg-h (upjpnrm-h upjisr-v as well)
jfmutil: malformed  kanji character: e38080

my system is below,
windows 10
texlive 2019

Another problem:

When I covert a vf2zvp, edit over and covert zvp2vf,
and convert vf2zvp again, there came out a bug, all subtype D0 D2 , D0 D3, D0 D4 lost.

Please SEE the attached files.

[new.zvp.txt](https://github.com/zr-tex8r/PXutil/files/3437895/new.zvp.txt)
[old.zvp.txt](https://github.com/zr-tex8r/PXutil/files/3437896/old.zvp.txt)

**Comment by zr-tex8r** [comment]
It was a bug: subtype information of type 0 was lost when there were no other types.
Fixed in the new version.

Thank you for your report.

**Comment by Steve-Cheung-emct** [comment]
Dear Mr. ZR.

When I use upLaTeX, I came up with such a problem, which I didn't know how to set up NFSS settings for European font. I look up many website in Japanese, no one introduced how to do NFSS settings for European font. I have no idea about how to print out English text by Japanese font, especially. (I am a Chinese user using upLaTeX for vertical book, in fact we can use Japanese fonts for traditional Chinese typesetting.)

Thank you very much.

**Comment by Steve-Cheung-emct** [comment]
Today, i find out a method to typeset English text by Japanese font, using `\userelfont\mcfamily` to print English text.

Thank you very much.
